### ISSUE TITLE
Unable to access the interface of openmeap-services-web

### ISSUE THREAD

**Issue by kkarthik21** [OpenMEAP/OpenMEAP#14]
Hi everyone,

I am unable to access an interface of openmeap-services-web thru http://localhost:8120/openmeap-services-web/interface.

It shows, 
HTTP Status 404 - /openmeap-services-web/interface
type Status report
message /openmeap-services-web/interface
description The requested resource is not available.
Apache Tomcat/7.0.42

Please advice!!

Cheers,
Karthik.K

**Comment by rahulrsystems** [comment]
Hi, I completed the setup from intall.txt in OpenMEAP package. but now I am trying to login into openmeap-admin-web using the URL [](http://localhost:8080/openmeap-admin-web/interface/ ) but no username password is working and there is no information about default username and password in nstall.txt file.
I tried the following users/password-

openMEAP/openMEAP
openshift/openMEAP
admin/openMEAP

there is no error on console.

Please help me!  Thanks in advance.:)

**Comment by thacher** [comment]
You need to update your tomcat-users.xml with the user and role.  https://github.com/OpenMEAP/OpenMEAP/blob/4393ff78de8e7d6ac8ed3247b965d4cd92335d57/server-side/openmeap-shared-serverside/src/com/openmeap/AuthorizerImpl.java
