### ISSUE TITLE
Open Meap

### ISSUE THREAD

**Issue by jaspreetkaurkhalsa** [OpenMEAP/OpenMEAP#22]
Hi, I have downloaded Open Meap project from it. and i was learning to install openmeap,  and  in one step it says "ant dist-all-web" so when i checked the folder name "dist" into the OPENMEAP project.
I found no dist folder in it.
kindly help. 
Thanks in advance

**Comment by jaspreetkaurkhalsa** [comment]
kindly reply, i am stucked with this issue! if anyone will help! it will be appreciated.
Thanks

**Comment by thacher** [comment]
Did you look in the /build-tools/dist folder? Did the build run successfully?

**Comment by thacher** [comment]
Issue resolved.
